CREATE DATABASE EMPRESA_SETORES;
USE EMPRESA_SETORES;

CREATE TABLE SETOR (
    ID_SETOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SETOR VARCHAR(65) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    FK_SETOR_SUP INT,

    CONSTRAINT FK_SETOR_SUPERIOR
        FOREIGN KEY (FK_SETOR_SUP) REFERENCES SETOR(ID_SETOR)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(65) NOT NULL,
    EMAIL VARCHAR(80),
    SALARIO DECIMAL(8,2) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    FK_SETOR INT NOT NULL,

    CONSTRAINT FK_FUNC_SETOR
        FOREIGN KEY (FK_SETOR) REFERENCES SETOR(ID_SETOR)
);

CREATE TABLE PROJETO (
    ID_PROJETO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROJETO VARCHAR(65) NOT NULL,
    DESCRICAO VARCHAR(255),
    DATA_INICIO DATE NOT NULL,
    DATA_PREV_TERMINO DATE,
    FK_SETOR INT NOT NULL,

    CONSTRAINT FK_PROJ_SETOR
        FOREIGN KEY (FK_SETOR) REFERENCES SETOR(ID_SETOR)
);

INSERT INTO SETOR (NOME_SETOR, SIGLA, FK_SETOR_SUP) VALUES
('Diretoria', 'DIR', NULL),
('Tecnologia da Informação', 'TI', 1),
('Suporte Técnico', 'SUP', 2),
('Financeiro', 'FIN', 1),
('Recursos Humanos', 'RH', 1);

INSERT INTO FUNCIONARIO (NOME, EMAIL, SALARIO, DATA_ADMISSAO, FK_SETOR) VALUES
('Ana Souza', 'ana.souza@empresa.com', 15000.00, '2015-03-15', 1),
('Carlos Eduardo', 'carlos.e@empresa.com', 12000.00, '2016-01-10', 2),
('Beatriz Lima', 'beatriz.lima@empresa.com', 4500.00, '2021-05-20', 2),
('Lucas Mendes', 'lucas.mendes@empresa.com', 3800.00, '2022-08-11', 2),
('Gabriel Rocha', 'gabriel.rocha@empresa.com', 5200.00, '2020-11-03', 3),
('Mariana Costa', 'mariana.c@empresa.com', 8900.00, '2019-07-01', 4);

INSERT INTO PROJETO (NOME_PROJETO, DESCRICAO, DATA_INICIO, DATA_PREV_TERMINO, FK_SETOR) VALUES
('Migração de Servidores', 'Atualização da infraestrutura de servidores', '2025-01-10', '2025-06-30', 2),
('Implantação de VPN', 'Implantação de rede privada para acesso remoto', '2025-02-01', '2025-05-15', 2),
('Sistema de Chamados', 'Ferramenta interna de abertura de tickets', '2025-03-01', '2025-09-01', 2),
('Fechamento Contábil Anual', 'Consolidação das contas do exercício', '2025-01-05', '2025-02-28', 4),
('Revisão Orçamentária', 'Revisão do orçamento do próximo ano fiscal', '2025-04-01', '2025-07-01', 4),
('Plano Estratégico 2026', 'Definição das metas estratégicas da empresa', '2025-01-15', '2025-12-20', 1);

SELECT
    F.NOME AS "FUNCIONÁRIO",
    S.NOME_SETOR AS "SETOR"
FROM FUNCIONARIO AS F JOIN SETOR AS S ON F.FK_SETOR = S.ID_SETOR;

SELECT
    P.NOME_PROJETO AS "PROJETO",
    S.NOME_SETOR AS "SETOR RESPONSÁVEL"
FROM PROJETO AS P JOIN SETOR AS S ON P.FK_SETOR = S.ID_SETOR;

SELECT
    F.NOME AS "FUNCIONÁRIO",
    F.DATA_ADMISSAO AS "DATA DE ADMISSÃO",
    S.NOME_SETOR AS "SETOR"
FROM FUNCIONARIO AS F JOIN SETOR AS S ON F.FK_SETOR = S.ID_SETOR
WHERE F.DATA_ADMISSAO > '2019-01-01';

SELECT
    SUB.NOME_SETOR AS "SETOR SUBORDINADO",
    SUP.NOME_SETOR AS "SETOR SUPERIOR"
FROM SETOR AS SUB JOIN SETOR AS SUP ON SUB.FK_SETOR_SUP = SUP.ID_SETOR;

SELECT
    SUB.NOME_SETOR AS "SETOR",
    SUP.NOME_SETOR AS "SETOR SUPERIOR"
FROM SETOR AS SUB LEFT JOIN SETOR AS SUP ON SUB.FK_SETOR_SUP = SUP.ID_SETOR;

SELECT
    SUB.NOME_SETOR AS "SETOR SUBORDINADO"
FROM SETOR AS SUB
WHERE SUB.FK_SETOR_SUP = 1;

SELECT
    S.NOME_SETOR AS "SETOR",
    F.NOME AS "FUNCIONÁRIO"
FROM SETOR AS S LEFT JOIN FUNCIONARIO AS F ON S.ID_SETOR = F.FK_SETOR;

SELECT
    F.NOME AS "FUNCIONÁRIO",
    F.SALARIO AS "SALÁRIO",
    S.NOME_SETOR AS "SETOR",
    CASE
        WHEN F.SALARIO <= 5000 THEN "SALÁRIO BAIXO"
        WHEN F.SALARIO > 5000 AND F.SALARIO <= 10000 THEN "SALÁRIO MÉDIO"
        ELSE "SALÁRIO ALTO"
    END AS "CLASSIFICAÇÃO SALARIAL"
FROM FUNCIONARIO AS F JOIN SETOR AS S ON F.FK_SETOR = S.ID_SETOR
ORDER BY F.SALARIO ASC;

SELECT
    F.NOME AS "FUNCIONÁRIO",
    S.NOME_SETOR AS "SETOR"
FROM FUNCIONARIO AS F JOIN SETOR AS S ON F.FK_SETOR = S.ID_SETOR
WHERE S.ID_SETOR IN (2, 4);

UPDATE SETOR SET FK_SETOR_SUP = 4 WHERE ID_SETOR = 5;

UPDATE SETOR SET FK_SETOR_SUP = NULL WHERE ID_SETOR = 5;