CREATE DATABASE DEPARTAMENTO2;
USE DEPARTAMENTO2;

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_DEPARTAMENTO VARCHAR(65) NOT NULL,
    ANDAR VARCHAR(25)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    SALARIO DECIMAL(8,2) NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(80),
    DATA_EMI DATE,
    FK_DEPARTAMENTO INT NOT NULL,
    FK_SUPERVISOR INT,
    
    CONSTRAINT FK_FUNC_DEPARTAMENTO 
        FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
        
    CONSTRAINT FK_FUNC_SUPERVISOR 
        FOREIGN KEY (FK_SUPERVISOR) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO, ANDAR) VALUES
('Recursos Humanos', '1º Andar'),
('Tecnologia da Informação', '2º Andar'),
('Financeiro', '3º Andar');


INSERT INTO FUNCIONARIO (SALARIO, NOME, EMAIL, DATA_EMI, FK_DEPARTAMENTO, FK_SUPERVISOR) VALUES
(12500.00, 'Ana Souza', 'ana.souza@empresa.com', '2018-03-15', 1, NULL),     -- ID 1
(15000.00, 'Carlos Eduardo', 'carlos.e@empresa.com', '2016-01-10', 2, NULL),  -- ID 2
(13800.00, 'Mariana Costa', 'mariana.c@empresa.com', '2019-07-01', 3, NULL);  -- ID 3


INSERT INTO FUNCIONARIO (SALARIO, NOME, EMAIL, DATA_EMI, FK_DEPARTAMENTO, FK_SUPERVISOR) VALUES
(4500.00, 'Beatriz Lima', 'beatriz.lima@empresa.com', '2021-05-20', 1, 1),
(3800.00, 'Lucas Mendes', 'lucas.mendes@empresa.com', '2022-08-11', 1, 1),
(8500.00, 'Gabriel Rocha', 'gabriel.rocha@empresa.com', '2020-11-03', 2, 2),
(6200.00, 'Fernanda Alves', 'fernanda.alves@empresa.com', '2023-02-14', 2, 2),
(5100.00, 'Rafael Torres', 'rafael.torres@empresa.com', '2021-09-01', 3, 3);


SELECT 
	FUNCIONARIO.NOME AS 'FUNCIONÁRIO',
    DEPARTAMENTO.NOME_DEPARTAMENTO AS 'DEPARTEMENTO'
FROM FUNCIONARIO 
JOIN DEPARTAMENTO ON FUNCIONARIO.FK_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO;


SELECT 
		FUNCIONARIO.NOME AS "NOME DO FUNCINÁRIO",
        FUNCIONARIO.SALARIO AS "SALÁRIO",
        FUNCIONARIO.DATA_EMI AS "DATA DE EMISSÃO"
FROM FUNCIONARIO JOIN DEPARTAMENTO ON FUNCIONARIO.FK_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
WHERE FUNCIONARIO.DATA_EMI > "2018-01-01";

SELECT
	FUNCIONARIO.NOME AS "NOME FUNCIONÁRIO",
    DEPARTAMENTO.NOME_DEPARTAMENTO AS "DEPARTAMENTO"
FROM FUNCIONARIO JOIN DEPARTAMENTO ON FUNCIONARIO.FK_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO AND DEPARTAMENTO.ID_DEPARTAMENTO IN (2,3);

SELECT
		FUNCIONARIO.NOME AS "NOME DO FUNCIONÁRIO",
        FUNCIONARIO.SALARIO AS "SALÁRIO"
FROM FUNCIONARIO JOIN DEPARTAMENTO ON FUNCIONARIO.FK_DEPARTAMENTO = DEPARTAMENTO.ID_DEPARTAMENTO
ORDER BY FUNCIONARIO.SALARIO DESC;



SELECT 
    SUPERVISOR.NOME AS "SUPERVISOR",
    SUBORDINADO.NOME AS "SUBORDINADO"
FROM FUNCIONARIO AS SUBORDINADO JOIN FUNCIONARIO AS SUPERVISOR ON SUBORDINADO.FK_SUPERVISOR = SUPERVISOR.ID_FUNCIONARIO;

SELECT 
	FUNC.NOME AS "NOME FUNCIONARIO",
    SUPE.NOME AS "SSUPERVISOR"
FROM FUNCIONARIO AS FUNC JOIN FUNCIONARIO AS SUPE ON FUNC.FK_SUPERVISOR= SUPE.ID_FUNCIONARIO
WHERE SUPE.NOME LIKE "A%";

SELECT 
	FUNC.NOME AS "NOME FUNCIONARIO",
    SUPE.NOME AS "SUPERVISOR",
    FUNC.SALARIO AS "SALARIO",
    CASE 
		WHEN FUNC.SALARIO <= 3000 THEN "SALÁRIO MÉDIO"
        WHEN FUNC.SALARIO >= 3500 THEN "SALÁRIO MÉDIO ALTO"
        WHEN FUNC.SALARIO > 6000 THEN "SALÁRIO ALTO"
    END AS "SALARIO FUNCIONARIO"
FROM FUNCIONARIO AS FUNC JOIN FUNCIONARIO AS SUPE ON FUNC.FK_SUPERVISOR= SUPE.ID_FUNCIONARIO
ORDER BY FUNC.SALARIO ASC;

UPDATE FUNCIONARIO SET FK_SUPERVISOR =2 WHERE ID_FUNCIONARIO = 3;
SELECT * FROM FUNCIONARIO;
UPDATE FUNCIONARIO SET FK_SUPERVISOR = NULL WHERE ID_FUNCIONARIO = 3 ;

DELETE FROM FUNCIONARIO WHERE ID_FUNCIONARIO!= FK_SUPERVISOR;
k) Excluir um funcionário que não seja supervisor de nenhum outro funcionário.

