CREATE DATABASE aula06_ccok_20262;
USE AULA06_CCOK_20262;
CREATE TABLE RESPONSAVEL(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(150),
CPF CHAR(11)
);
CREATE TABLE empresa(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45),
cnpj CHAR(14) UNIQUE NOT NULL,
FK_responsavel INT UNIQUE,
CONSTRAINT CHFK_RESPONSAVEL
FOREIGN KEY (FK_responsavel) REFERENCES
responsavel(id)
);

CREATE TABLE funcionario (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(150),
cpf CHAR(11) UNIQUE NOT NULL,
salario DECIMAL(10,2),
FK_empresa int,
CONSTRAINT CKFKempresa
	FOREIGN KEY (FK_empresa) REFERENCES
    empresa(id)
);

INSERT INTO RESPONSAVEL(NOME,CPF) VALUES
('CLARA','11111111111'),
('VICTOR','22222222222');

INSERT INTO EMPRESA (NOME,CNPJ,FK_RESPONSAVEL) VALUES
('SPTECH','11111111111111',1),
('BRADESCO','22222222222222',2);

INSERT INTO FUNCIONARIO(NOME,CPF,SALARIO,FK_EMPRESA)VALUES
('ISA','33333333333',2000.0,1),
('VICTOR','44444444444',5000.0,1);


SELECT
E.NOME AS 'NOME EMPRESA',
R.NOME 'NOME RESPONSAVEL',
F.NOME 'NOME FUNC' 
FROM RESPONSAVEL AS R
	JOIN EMPRESA AS e
    ON R.FK_RESPONSAVEL = R.ID
    JOIN FUNCIONARIO AS F
    ON F.FK_EMPRESA = E.ID;
    
    
SELECT 
	EMPRESA.NOME,
    FUNCIONARIO.NOME
FROM 
EMPRESA LEFT JOIN FUNCIONARIO
    ON FUNCIONARIO.FK_EMPRESA = EMPRESA.ID;
    

SELECT 
	EMPRESA.NOME AS 'NOME EMPRESA',
    IFNULL(FUNCIONARIO.NOME,'SEM FUNCIONARIO') AS FUNCIONARIO
FROM EMPRESA LEFT JOIN FUNCIONARIO
ON FUNCIONARIO.FK_EMPRESA = EMPRESA.ID
WHERE EMPRESA.NOME LIKE 'S%' OR EMPRESA.NOME LIKE 'B%'



/*
COMANDO PARA CONCEDER PERMISSÃO: GRANT
COMANDO PARA REVOGAR PERMISSÃO: REVOKE
COMANDO PARA CRIAR USUÁRIOS: CREATE
COMANDO PARA APAGAR USUÁRIOS: DROP
COMANDO PARA ATUALIZAR PERMISSÕES : FLUSH PRIVILEGES

*/
ORDER BY EMPRESA.NOME
;