CREATE DATABASE BIBLIOTECA02;
USE BIBLIOTECA02;

CREATE TABLE AUTOR(
id_autor INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome_autor VARCHAR(65) NOT NULL,
nacionalidade VARCHAR(45),
data_nasc DATE NOT NULL
);
CREATE TABLE LIVRO (
id_livro INT PRIMARY KEY AUTO_INCREMENT,
titulo_livro VARCHAR(45),
data_publi DATE,
qtd_pag INT,
CONSTRAINT CH_MINIMO_PAG CHECK(QTD_PAG >0),
preco DECIMAL(6,2),
FK_LIVRO INT,
CONSTRAINT CH_FK_LIVRO FOREIGN KEY (FK_LIVRO) REFERENCES AUTOR(ID_AUTOR)
);


SELECT * FROM LIVRO;

SELECT
	L.TITULO_LIVRO AS "TITULO LIVRO ",
    A.NOME_AUTOR AS "NOME DO AUTOR",
    L.data_publi AS "DATA DE LANÇAMENTO"
FROM LIVRO AS L JOIN AUTOR AS A ON L.FK_LIVRO = A.ID_AUTOR;


SELECT
	L.TITULO_LIVRO AS "TÍTULO",
	L.DATA_PUBLI AS "ANO PUBLICAÇÃO",
    A.NOME_AUTOR AS "NOME DO AUTOR"
FROM LIVRO AS L JOIN AUTOR AS A ON L.FK_LIVRO = A.ID_AUTOR
WHERE L.DATA_PUBLI >"1960-01-01" ORDER BY L.DATA_PUBLI ASC;

SELECT
	L.TITULO_LIVRO AS "TÍTULO",
	L.DATA_PUBLI AS "ANO PUBLICAÇÃO",
    A.NOME_AUTOR AS "NOME DO AUTOR"
FROM LIVRO AS L JOIN AUTOR AS A ON L.FK_LIVRO = A.ID_AUTOR
WHERE A.NOME_AUTOR = "Machado de Assis";

SELECT TITULO_LIVRO FROM LIVRO WHERE PRECO >=20 AND PRECO <=45;

SELECT
	L.TITULO_LIVRO AS "TÍTULO",
	L.DATA_PUBLI AS "ANO PUBLICAÇÃO",
    A.NOME_AUTOR AS "NOME DO AUTOR",
    CASE 
		WHEN L.QTD_PAG <=200 THEN "LIVRO CURTO"
        WHEN L.QTD_PAG >200 AND L.QTD_PAG <=400 THEN "LIVRO MÉDIO"
        ELSE "LIVRO GRANDE"
	END AS "TAMANHO LIVRO"
FROM LIVRO AS L JOIN AUTOR AS A ON L.FK_LIVRO = A.ID_AUTOR
ORDER BY L.PRECO ASC;

UPDATE LIVRO SET PRECO =20 WHERE ID_LIVRO = 10;

DELETE FROM LIVRO WHERE ID_LIVRO = 10;

SELECT
	L.TITULO_LIVRO AS "TÍTULO",
	L.DATA_PUBLI AS "ANO PUBLICAÇÃO",
    A.NOME_AUTOR AS "NOME DO AUTOR"
FROM LIVRO AS L JOIN AUTOR AS A ON L.FK_LIVRO = A.ID_AUTOR
ORDER BY L.DATA_PUBLI ASC;

INSERT INTO AUTOR (nome_autor, nacionalidade, data_nasc) VALUES
('Machado de Assis', 'Brasileira', '1839-06-21'),
('J.K. Rowling', 'Britânica', '1965-07-31'),
('George Orwell', 'Britânica', '1903-06-25'),
('Clarice Lispector', 'Brasileira', '1920-12-10'),
('Stephen King', 'Americana', '1947-09-21');


INSERT INTO LIVRO (titulo_livro, data_publi, qtd_pag, preco, FK_LIVRO) VALUES
('Dom Casmurro', '1899-01-01', 256, 29.90, 1),
('Memórias Póstumas de Brás Cubas', '1881-01-01', 320, 34.50, 1),
('Harry Potter e a Pedra Filosofal', '1997-06-26', 223, 49.90, 2),
('Harry Potter e a Câmara Secreta', '1998-07-02', 251, 52.00, 2),
('1984', '1949-06-08', 336, 39.90, 3),
('A Hora da Estrela', '1977-10-26', 104, 25.00, 4),
('Laços de Família', '1960-01-01', 144, 28.00, 4),
('O Iluminado', '1977-01-28', 464, 59.90, 5);


