USE sprint01;

CREATE TABLE ALUGUEL(
    ID INT PRIMARY KEY AUTO_INCREMENT;
    NOME VARCHAR(90),
    SOBRENOME VARCHAR(90),
    VALOR_TOTAL DECIMAL(6,2),
    STATUS_ALUGUEL TINYINT,CONSTRAINT CHK_STATUS CHECK(STATUS_ALUGUEL('FINALIZADO','EM ANDAMENTO'))

);