CREATE DATABASE sprint01;
USE sprint01;

CREATE TABLE ALUGUEL(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(90),
    SOBRENOME VARCHAR(90),
    VALOR_TOTAL DECIMAL(7,2),
    STATUS_ALUGUEL VARCHAR(90),CONSTRAINT CHK_STATUS CHECK(STATUS_ALUGUEL IN('FINALIZADO','EM_ANDAMENTO'))

);
INSERT INTO ALUGUEL (NOME,SOBRENOME,VALOR_TOTAL,STATUS_ALUGUEL) VALUES ('Cristiano','Ronaldo',10000,'EM_ANDAMENTO');
	SELECT CONCAT(NOME,' ',SOBRENOME) AS 'NOME COMPLETO',VALOR_TOTAL,
    
    CASE 
		WHEN STATUS_ALUGUEL = 'FINALIZADO' THEN 'CONCLUIDO'
        WHEN STATUS_ALUGUEL = 'EM_ANDAMENTO' THEN 'EM ANDAMENTO'
        ELSE 'CANCELADO'
	END AS 'SITUAÇÃO'
    FROM ALUGUEL ORDER BY NOME ASC;
    
    