CREATE DATABASE ESCOLA_TEC2;
USE ESCOLA_TEC2;

CREATE TABLE ALUNO(
ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
RA VARCHAR(25),
NOME_ALUNO VARCHAR(45),
EMAIL VARCHAR(125),
DATA_NASC DATE
);

CREATE TABLE CURSO(
ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(45),
SIGLA_CURSO CHAR(5),
DURACAO_CURSO INT
);

CREATE TABLE TURMA(
ID_TURMA INT,
CODIGO VARCHAR(45),
SEMESTRE_INGRESSO VARCHAR(45),
FK_ALUNO INT,
FK_CURSO INT,
CONSTRAINT CHK_FK_ALUNO FOREIGN KEY(FK_ALUNO) REFERENCES ALUNO(ID_ALUNO),
CONSTRAINT CHK_FK_CURSO FOREIGN KEY(FK_CURSO) REFERENCES CURSO(ID_CURSO)
);

SELECT 
	T.CODIGO AS "CÓDIGO DA TURMA",
    C.NOME AS "NOME DO CURSO"
FROM TURMA AS T JOIN CURSO AS C ON T.FK_CURSO = C.ID_CURSO;

SELECT 
	A.NOME_ALUNO AS "NOME DO ALUNO",
    A.RA AS "RA DO ALUNO",
	T.CODIGO AS "CÓDIGO DA TURMA",
    C.NOME AS "NOME DO CURSO"
FROM ALUNO AS A 
JOIN TURMA AS T ON T.FK_ALUNO = A.ID_ALUNO
JOIN CURSO AS C ON T.FK_CURSO = C.ID_CURSO;

SELECT 
	A.NOME_ALUNO AS "NOME DO ALUNO",
	T.CODIGO AS "CÓDIGO DA TURMA",
    C.NOME AS "NOME DO CURSO"
FROM ALUNO AS A 
JOIN TURMA AS T ON T.FK_ALUNO = A.ID_ALUNO
JOIN CURSO AS C ON T.FK_CURSO = C.ID_CURSO
WHERE C.SIGLA_CURSO = "ads";

SELECT 
    A.NOME_ALUNO AS "NOME DO ALUNO",
    T.CODIGO AS "CÓDIGO DA TURMA",
    T.SEMESTRE_INGRESSO AS "SEMESTRE DE INGRESSO",
    CASE 
        WHEN T.SEMESTRE_INGRESSO < '2026-1' THEN 'VETERANO ANTIGO'
        WHEN T.SEMESTRE_INGRESSO = '2026-1' THEN 'CALOURO ADMITIDO'
        ELSE 'INGRESSO FUTURO'
    END AS "CLASSIFICAÇÃO"
FROM ALUNO AS A 
JOIN TURMA AS T ON T.FK_ALUNO = A.ID_ALUNO;
 
SELECT 
    C.NOME AS "NOME DO CURSO",
    C.SIGLA_CURSO AS "SIGLA",
    T.CODIGO AS "CÓDIGO DA TURMA",
    T.SEMESTRE_INGRESSO AS "SEMESTRE"
FROM CURSO AS C
LEFT JOIN TURMA AS T ON C.ID_CURSO = T.FK_CURSO;

ALTER TABLE ALUNO ADD TELEFONE VARCHAR(15);

UPDATE ALUNO SET TELEFONE = '(11) 99999-1111' WHERE ID_ALUNO = 1;

UPDATE ALUNO SET TELEFONE = '(11) 98888-2222' WHERE ID_ALUNO = 2;

INSERT INTO ALUNO (RA, NOME_ALUNO, EMAIL, DATA_NASC) VALUES
('RA001', 'Carlos Silva', 'carlos@email.com', '2005-03-15'),
('RA002', 'Beatriz Rocha', 'beatriz@email.com', '2004-07-22'),
('RA003', 'Marcos Pires', 'marcos@email.com', '2005-01-10'),
('RA004', 'Julia Almeida', 'julia@email.com', '2006-11-05'),
('RA005', 'Lucas Mendes', 'lucas.m@email.com', '2004-05-18'),
('RA006', 'Fernanda Lima', 'fernanda@email.com', '2005-09-30'),
('RA007', 'Gabriel Costa', 'gabriel@email.com', '2003-12-12'),
('RA008', 'Mariana Souza', 'mariana@email.com', '2005-04-25');

INSERT INTO CURSO (NOME, SIGLA_CURSO, DURACAO_CURSO) VALUES
('Análise e Desenvolvimento de Sistemas', 'ADS', 4),
('Redes de Computadores', 'REDES', 4),
('Gestão de TI', 'GTI', 4);

INSERT INTO TURMA (ID_TURMA, CODIGO, SEMESTRE_INGRESSO, FK_ALUNO, FK_CURSO) VALUES
(1, 'ADS-101', '2026-1', 1, 1),
(1, 'ADS-101', '2026-1', 2, 1),
(1, 'ADS-101', '2026-1', 3, 1),
(2, 'ADS-102', '2026-1', 4, 1),
(2, 'ADS-102', '2026-1', 5, 1),
(3, 'RED-201', '2026-1', 6, 2),
(3, 'RED-201', '2026-1', 7, 2),
(4, 'RED-202', '2026-2', 8, 2);
